// flow-typed signature: d6f8654062f29e2337da126052c5ec55
// flow-typed version: <<STUB>>/chrome-webstore-upload-cli_v^1.2.1/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrome-webstore-upload-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrome-webstore-upload-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chrome-webstore-upload-cli/config' {
  declare module.exports: any;
}

declare module 'chrome-webstore-upload-cli/util' {
  declare module.exports: any;
}

declare module 'chrome-webstore-upload-cli/wrapper' {
  declare module.exports: any;
}

declare module 'chrome-webstore-upload-cli/zipdir' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chrome-webstore-upload-cli/config.js' {
  declare module.exports: $Exports<'chrome-webstore-upload-cli/config'>;
}
declare module 'chrome-webstore-upload-cli/index' {
  declare module.exports: $Exports<'chrome-webstore-upload-cli'>;
}
declare module 'chrome-webstore-upload-cli/index.js' {
  declare module.exports: $Exports<'chrome-webstore-upload-cli'>;
}
declare module 'chrome-webstore-upload-cli/util.js' {
  declare module.exports: $Exports<'chrome-webstore-upload-cli/util'>;
}
declare module 'chrome-webstore-upload-cli/wrapper.js' {
  declare module.exports: $Exports<'chrome-webstore-upload-cli/wrapper'>;
}
declare module 'chrome-webstore-upload-cli/zipdir.js' {
  declare module.exports: $Exports<'chrome-webstore-upload-cli/zipdir'>;
}
