// flow-typed signature: ea3ab765b3e92e46827761a2bbbab265
// flow-typed version: <<STUB>>/webextension-toolbox_v^4.0.3/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webextension-toolbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webextension-toolbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webextension-toolbox/src/compile' {
  declare module.exports: any;
}

declare module 'webextension-toolbox/src/preset' {
  declare module.exports: any;
}

declare module 'webextension-toolbox/src/utils/get-config-file-config' {
  declare module.exports: any;
}

declare module 'webextension-toolbox/src/utils/get-extension-file-type' {
  declare module.exports: any;
}

declare module 'webextension-toolbox/src/utils/get-extension-info' {
  declare module.exports: any;
}

declare module 'webextension-toolbox/src/utils/global' {
  declare module.exports: any;
}

declare module 'webextension-toolbox/src/webpack-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webextension-toolbox/index' {
  declare module.exports: $Exports<'webextension-toolbox'>;
}
declare module 'webextension-toolbox/index.js' {
  declare module.exports: $Exports<'webextension-toolbox'>;
}
declare module 'webextension-toolbox/src/compile.js' {
  declare module.exports: $Exports<'webextension-toolbox/src/compile'>;
}
declare module 'webextension-toolbox/src/preset.js' {
  declare module.exports: $Exports<'webextension-toolbox/src/preset'>;
}
declare module 'webextension-toolbox/src/utils/get-config-file-config.js' {
  declare module.exports: $Exports<'webextension-toolbox/src/utils/get-config-file-config'>;
}
declare module 'webextension-toolbox/src/utils/get-extension-file-type.js' {
  declare module.exports: $Exports<'webextension-toolbox/src/utils/get-extension-file-type'>;
}
declare module 'webextension-toolbox/src/utils/get-extension-info.js' {
  declare module.exports: $Exports<'webextension-toolbox/src/utils/get-extension-info'>;
}
declare module 'webextension-toolbox/src/utils/global.js' {
  declare module.exports: $Exports<'webextension-toolbox/src/utils/global'>;
}
declare module 'webextension-toolbox/src/webpack-config.js' {
  declare module.exports: $Exports<'webextension-toolbox/src/webpack-config'>;
}
